"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, Bot, ChevronRight, Eye, LockKeyhole, RotateCcw, ShieldCheck, UserRoundCheck, WandSparkles } from "lucide-react";
import { AppShell, StatusPill } from "@/app/components/app-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

type Kind="Auto"|"Approval"|"Expert";
type Issue={id:string;title:string;area:string;impact:"High"|"Medium";kind:Kind;credits:number;why:string;before:string;after:string;confidence:number};
type ModelContext={registerTool:(tool:Record<string,unknown>,options?:{signal?:AbortSignal})=>void|Promise<void>};

const issues:Issue[]=[
  {id:"answer-block",title:"Add an extractable answer block",area:"Content",impact:"High",kind:"Auto",credits:10,why:"AI systems can identify concise, direct answers more reliably when the page exposes a self-contained response.",before:"Our platform gives teams powerful workflow capabilities across many use cases.",after:"Acme is a workflow automation platform for small teams. It connects recurring tasks, approvals, and handoffs in one workspace.",confidence:91},
  {id:"org-schema",title:"Complete Organization schema",area:"Technical",impact:"High",kind:"Auto",credits:10,why:"Incomplete entity identifiers make it harder to connect the website with the same brand across trusted sources.",before:'{ "@type": "Organization", "name": "Acme" }',after:'{ "@type": "Organization", "name": "Acme", "url": "https://acme.example", "sameAs": ["verified profiles"] }',confidence:94},
  {id:"entity-description",title:"Clarify the primary brand description",area:"Entity",impact:"High",kind:"Approval",credits:15,why:"The current wording shifts between three categories, creating ambiguity about what the company actually provides.",before:"Acme helps organizations do more with technology and collaboration.",after:"Acme provides workflow automation software for small distributed teams managing approvals, handoffs, and recurring operations.",confidence:86},
  {id:"faq-structure",title:"Restructure high-intent FAQs",area:"Content",impact:"Medium",kind:"Approval",credits:10,why:"Questions exist, but answers mix multiple intents and do not resolve the commercial query directly.",before:"How does it work? Acme has many tools and features for modern businesses...",after:"What does Acme automate? Acme automates recurring approvals, task handoffs, and status updates for small teams.",confidence:82},
  {id:"internal-links",title:"Connect service pages to proof assets",area:"Architecture",impact:"Medium",kind:"Auto",credits:15,why:"Relevant case evidence is isolated from the pages expected to support recommendation decisions.",before:"Service page → no evidence link",after:"Service page → relevant case study → methodology",confidence:88},
  {id:"authority",title:"Build third-party authority signals",area:"Authority",impact:"High",kind:"Expert",credits:0,why:"External mentions and credible citations require editorial strategy and outreach, not an automated promise.",before:"Limited independent brand references",after:"Expert scope: evidence asset, source map, outreach plan, and measurable coverage",confidence:79},
];

export function FixCenterExperience(){
  const [selected,setSelected]=useState<Issue|null>(null);
  const auto=useMemo(()=>issues.filter(x=>x.kind==="Auto"),[]); const approval=useMemo(()=>issues.filter(x=>x.kind==="Approval"),[]); const expert=useMemo(()=>issues.filter(x=>x.kind==="Expert"),[]);
  const stage=useCallback((id:string)=>{const found=issues.find(x=>x.id===id);if(!found)throw new Error("Unknown issue id.");setSelected(found);return {issueId:found.id,title:found.title,executionType:found.kind,credits:found.credits,status:"preview_opened",applicationEnabled:false};},[]);
  useEffect(()=>{const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const registration=context.registerTool({name:"stage_fix_preview",title:"Preview a Recomvia fix",description:"Open the same before/after preview used in Recomvia Fix Center for one detected issue. This stages a preview and does not modify a live website.",inputSchema:{type:"object",properties:{issueId:{type:"string",enum:issues.map(x=>x.id)}},required:["issueId"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=="object"||typeof (input as {issueId?:unknown}).issueId!=="string")throw new Error("issueId is required.");return stage((input as {issueId:string}).issueId)}},{signal:lifecycle.signal});Promise.resolve(registration).catch(()=>undefined);return()=>lifecycle.abort()},[stage]);

  function list(rows:Issue[]){return <div className="space-y-3">{rows.map(issue=><Card key={issue.id} className="rounded-[20px] border-slate-200 bg-white py-0 shadow-none"><CardContent className="flex flex-col gap-5 p-5 lg:flex-row lg:items-center"><span className={`grid size-11 shrink-0 place-items-center rounded-2xl ${issue.kind==="Auto"?"bg-blue-50 text-blue-600":issue.kind==="Approval"?"bg-violet-50 text-violet-600":"bg-amber-50 text-amber-700"}`}>{issue.kind==="Auto"?<Bot className="size-5"/>:issue.kind==="Approval"?<Eye className="size-5"/>:<UserRoundCheck className="size-5"/>}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-extrabold">{issue.title}</h3><StatusPill tone="warn">Catalog preview</StatusPill></div><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{issue.why}</p><div className="mt-3 flex flex-wrap gap-2"><StatusPill tone={issue.impact==="High"?"bad":"warn"}>{issue.impact} impact</StatusPill><StatusPill tone="info">{issue.area}</StatusPill><span className="text-xs font-bold text-slate-400">Illustrative confidence {issue.confidence}%</span></div></div><div className="flex items-center justify-between gap-4 border-t border-slate-100 pt-4 lg:min-w-[220px] lg:border-l lg:border-t-0 lg:pl-5 lg:pt-0"><div>{issue.kind==="Expert"?<span className="text-sm font-bold text-slate-600">Scoped quote</span>:<><p className="text-xl font-extrabold">{issue.credits}</p><p className="text-[11px] text-slate-500">provisional credits</p></>}</div><Button variant={issue.kind==="Expert"?"outline":"default"} className="rounded-xl" onClick={()=>stage(issue.id)}>{issue.kind==="Expert"?"Preview expert route":"Preview example"}<ChevronRight className="size-4"/></Button></div></CardContent></Card>)}</div>}

  return <AppShell title="Fix catalog preview" description="Preview the planned execution routes. Credits cannot be purchased or consumed until billing, versioning, and rollback are connected." action={<div className="flex items-center gap-3 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-2.5"><LockKeyhole className="size-5 text-amber-700"/><div><p className="text-xs text-amber-700">Private beta</p><p className="font-extrabold text-amber-950">Application locked</p></div></div>}>
    <div className="mb-5 rounded-2xl border border-blue-200 bg-blue-50/70 px-4 py-3 text-sm text-blue-900"><strong>Preview only:</strong> no website change is applied and no Fix Credits are charged from this screen.</div>
    <div className="mb-6 grid gap-4 sm:grid-cols-3">{[
      {value:String(auto.length),label:"Auto-fix examples",Icon:Bot,color:"bg-blue-50 text-blue-600"},
      {value:String(approval.length),label:"Approval examples",Icon:Eye,color:"bg-violet-50 text-violet-600"},
      {value:String(expert.length),label:"Expert examples",Icon:UserRoundCheck,color:"bg-amber-50 text-amber-700"}
    ].map(({value,label,Icon,color})=><Card key={label} className="rounded-[20px] border-slate-200 py-0 shadow-none"><CardContent className="flex items-center gap-4 p-5"><span className={`grid size-11 place-items-center rounded-2xl ${color}`}><Icon className="size-5"/></span><div><p className="text-2xl font-extrabold">{value}</p><p className="text-sm text-slate-500">{label}</p></div></CardContent></Card>)}</div>
    <Tabs defaultValue="all" className="gap-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><TabsList className="h-auto flex-wrap rounded-xl bg-slate-200/60 p-1"><TabsTrigger value="all" className="px-4 py-2.5">All issues</TabsTrigger><TabsTrigger value="auto" className="px-4 py-2.5">Auto-fix</TabsTrigger><TabsTrigger value="approval" className="px-4 py-2.5">Needs approval</TabsTrigger><TabsTrigger value="expert" className="px-4 py-2.5">Expert</TabsTrigger></TabsList><Button variant="outline" className="rounded-xl" onClick={()=>stage("answer-block")}><WandSparkles className="size-4"/>Preview first safe fix</Button></div><TabsContent value="all">{list(issues)}</TabsContent><TabsContent value="auto">{list(auto)}</TabsContent><TabsContent value="approval">{list(approval)}</TabsContent><TabsContent value="expert">{list(expert)}</TabsContent></Tabs>
    <Dialog open={Boolean(selected)} onOpenChange={open=>!open&&setSelected(null)}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-[24px] sm:max-w-2xl">{selected&&<><DialogHeader><div className="mb-2 flex items-center gap-2"><StatusPill tone={selected.kind==="Expert"?"warn":"info"}>{selected.kind} fix</StatusPill><StatusPill tone="warn">Preview only</StatusPill></div><DialogTitle className="text-2xl font-extrabold">{selected.title}</DialogTitle><DialogDescription className="leading-6">{selected.why}</DialogDescription></DialogHeader><div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-red-100 bg-red-50/50 p-4"><p className="mb-3 text-xs font-bold uppercase tracking-wider text-red-600">Example current version</p><pre className="whitespace-pre-wrap font-sans text-sm leading-6 text-slate-700">{selected.before}</pre></div><div className="rounded-2xl border border-emerald-100 bg-emerald-50/50 p-4"><p className="mb-3 text-xs font-bold uppercase tracking-wider text-emerald-600">Example recommended version</p><pre className="whitespace-pre-wrap font-sans text-sm leading-6 text-slate-700">{selected.after}</pre></div></div><div className="flex items-start gap-3 rounded-2xl bg-slate-50 p-4 text-sm text-slate-600"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-blue-600"/><p><strong className="text-[#07111f]">Application remains locked:</strong> production changes require a finding from a live scan, explicit approval, a version record, audit log, and rollback point.</p></div><DialogFooter className="items-center sm:justify-between"><div className="text-start">{selected.kind==="Expert"?<p className="text-sm font-bold">Expert scope · no credits charged</p>:<p><strong className="text-xl">{selected.credits}</strong> <span className="text-sm text-slate-500">provisional credits</span></p>}</div><Button asChild className="rounded-xl bg-[#07111f]"><Link href="/contact">Join the fix beta <ArrowRight className="size-4"/></Link></Button></DialogFooter></>}</DialogContent></Dialog>
    <div className="mt-6 flex flex-col gap-4 rounded-[22px] border border-slate-200 bg-[#07111f] p-6 text-white sm:flex-row sm:items-center"><RotateCcw className="size-6 text-cyan-300"/><div className="flex-1"><p className="font-bold">Post-fix measurement closes the loop</p><p className="mt-1 text-sm text-slate-400">Essential or higher remains required so every approved fix can be measured again.</p></div><Button asChild className="rounded-xl bg-white text-[#07111f]"><Link href="/pricing">View plans</Link></Button></div>
  </AppShell>
}
