import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpen, CalendarDays, Clock3, Radar } from "lucide-react";
import { PublicShell } from "@/app/components/public-shell";
import { StatusPill } from "@/app/components/app-shell";
import { Card, CardContent } from "@/components/ui/card";
import { articles, SITE_URL } from "@/lib/articles";

export const metadata: Metadata = {
  title: { absolute: "AI Visibility Research & Guides | Recomvia" },
  description: "Evidence-led guides to AI visibility optimization, AEO, GEO, technical discovery, content extractability, entity clarity, citations, and measurement.",
  alternates: { canonical: `${SITE_URL}/blog` },
  openGraph: { title: "AI Visibility Research & Guides | Recomvia", description: "Practical, evidence-led guidance for measuring and improving brand visibility in AI answers.", type: "website", url: `${SITE_URL}/blog` },
};

export default function BlogPage(){
  const [featured,...rest]=articles;
  const collectionSchema={"@context":"https://schema.org","@type":"CollectionPage",name:"Recomvia AI Visibility Research",description:"Evidence-led guides to AI visibility optimization, AEO, GEO, and generative search measurement.",url:`${SITE_URL}/blog`,mainEntity:{"@type":"ItemList",itemListElement:articles.map((article,index)=>({"@type":"ListItem",position:index+1,url:`${SITE_URL}/blog/${article.slug}`,name:article.title}))}};
  return <PublicShell><main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(collectionSchema).replace(/</g,"\\u003c")}}/>
    <section className="relative overflow-hidden border-b border-slate-200"><div className="signal-grid absolute inset-0"/><div className="relative mx-auto max-w-[1240px] px-5 py-16 sm:px-8 sm:py-24"><div className="grid gap-10 lg:grid-cols-[.78fr_1.22fr] lg:items-end"><div><p className="flex items-center gap-2 text-sm font-bold uppercase tracking-[.16em] text-blue-600"><Radar className="size-4"/>Recomvia Research</p><h1 className="mt-4 text-4xl font-extrabold tracking-[-.05em] sm:text-6xl">AI visibility,<br/><span className="gradient-text">without the myths.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Original, practical guidance for teams that need to understand how AI systems discover, describe, cite, and recommend brands.</p><div className="mt-7 flex flex-wrap gap-3 text-sm font-semibold text-slate-500"><span>{articles.length} in-depth guides</span><span>•</span><span>Evidence-first methodology</span><span>•</span><span>Reviewed September 2026</span></div></div>
      <Link href={`/blog/${featured.slug}`} className="group rounded-[28px] border border-blue-200 bg-[#07111f] p-7 text-white shadow-[0_28px_70px_rgba(7,17,31,.15)] transition hover:-translate-y-1 sm:p-9"><div className="flex items-center justify-between"><StatusPill tone="info">Featured guide</StatusPill><BookOpen className="size-5 text-cyan-300"/></div><p className="mt-10 text-sm font-bold text-cyan-300">{featured.category}</p><h2 className="mt-3 text-2xl font-extrabold leading-tight tracking-[-.025em] sm:text-3xl">{featured.title}</h2><p className="mt-4 leading-7 text-slate-300">{featured.excerpt}</p><div className="mt-7 flex items-center justify-between border-t border-white/10 pt-5 text-sm"><span className="text-slate-400">{featured.readingTime}</span><span className="flex items-center gap-2 font-bold">Read the guide <ArrowRight className="size-4 transition group-hover:translate-x-1"/></span></div></Link></div></div></section>
    <section className="mx-auto max-w-[1240px] px-5 py-20 sm:px-8"><div className="mb-9 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.14em] text-blue-600">Knowledge library</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight">Built to answer real questions.</h2></div><p className="max-w-md text-sm leading-6 text-slate-500">Every guide includes a direct answer, implementation detail, limitations, FAQs, source links, and related reading.</p></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{rest.map(article=><Card key={article.slug} className="group rounded-[22px] border-slate-200 py-0 shadow-none transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl"><CardContent className="flex h-full flex-col p-6"><div className="flex items-center justify-between gap-3"><StatusPill tone={article.category==="Technical"?"info":article.category==="Authority"?"warn":"good"}>{article.category}</StatusPill><span className="flex items-center gap-1.5 text-xs text-slate-400"><Clock3 className="size-3.5"/>{article.readingTime}</span></div><h3 className="mt-7 text-xl font-extrabold leading-7 tracking-[-.02em]">{article.title}</h3><p className="mt-3 flex-1 text-sm leading-6 text-slate-600">{article.excerpt}</p><div className="mt-6 flex items-center justify-between border-t border-slate-100 pt-5"><span className="flex items-center gap-1.5 text-xs text-slate-400"><CalendarDays className="size-3.5"/>Sep 13, 2026</span><Link href={`/blog/${article.slug}`} className="flex items-center gap-2 text-sm font-bold text-blue-700">Read <ArrowRight className="size-4 transition group-hover:translate-x-1"/></Link></div></CardContent></Card>)}</div></section>
    <section className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-[1240px] flex-col gap-5 px-5 py-12 sm:flex-row sm:items-center sm:justify-between sm:px-8"><div><h2 className="text-2xl font-extrabold">Measure your own AI visibility.</h2><p className="mt-2 text-sm text-slate-600">Turn the concepts in these guides into a prioritized, evidence-linked report.</p></div><Link href="/" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-bold text-white">Run a free score <ArrowRight className="size-4"/></Link></div></section>
  </main></PublicShell>
}
