import type { Metadata } from "next";
import { NavigationLink as Link } from "@/app/components/navigation-link";
import { ArrowRight, BarChart3, Bot, Check, CircleAlert, Clock3, FileSearch, Globe2, Repeat2, Scale, ShieldCheck } from "lucide-react";
import { PublicShell } from "@/app/components/public-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { SITE_URL } from "@/lib/articles";

export const metadata: Metadata = {
  title: { absolute: "Recomvia Measurement Methodology" },
  description: "How Recomvia separates live website readiness from actual AI answer visibility, records evidence, versions scores, and states measurement limits.",
  alternates: { canonical: `${SITE_URL}/methodology` },
  openGraph: { title: "Recomvia Measurement Methodology", description: "A transparent methodology for readiness and AI visibility evidence.", url: `${SITE_URL}/methodology`, type: "website" },
};

const dimensions=[
  ["Actual AI visibility","Observed mentions, recommendations, citations, position, coverage, and consistency across defined prompt runs."],
  ["Authority & entity","How clearly the brand, organization, authors, evidence, and trusted external references connect."],
  ["Content readiness","Answer extractability, intent alignment, factual density, completeness, freshness, and citation support."],
  ["Technical AEO","Crawlability, indexability, structured data, architecture, rendering, canonicals, and crawler policy."],
  ["Language & market fit","A distinct measurement for every language, country, commercial intent, and local competitive context."],
];
const stages=[
  ["1","Discover context","Identify the brand, category, services, markets, languages, and candidate competitors."],
  ["2","Generate prompts","Create high-intent informational, commercial, comparison, recommendation, and transactional questions."],
  ["3","Run and label","Store engine surface, model/search mode, language, country, timestamp, and run number."],
  ["4","Extract evidence","Measure observable mentions, citations, positions, sources, sentiment, and factual accuracy."],
  ["5","Audit readiness","Inspect technical access, content structure, entity clarity, authority, and market fit."],
  ["6","Score with confidence","Combine actual visibility and readiness while retaining volatility and confidence labels."],
];

export default function Methodology(){return <PublicShell><main>
  <section className="relative overflow-hidden border-b border-slate-200 bg-[#07111f] text-white"><div className="signal-grid absolute inset-0 opacity-20"/><div className="relative mx-auto max-w-[1000px] px-5 py-20 sm:px-8 sm:py-28"><p className="text-sm font-bold uppercase tracking-[.16em] text-cyan-300">Public methodology</p><h1 className="mt-4 max-w-4xl text-4xl font-extrabold tracking-[-.05em] sm:text-6xl">A score you can question.<br/>Evidence you can inspect.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Recomvia does not turn unstable AI answers into false certainty. We document what was tested, how it was tested, and what the result cannot prove.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild className="h-11 rounded-xl bg-white font-bold text-[#07111f]"><Link href="/">Run free score <ArrowRight className="size-4"/></Link></Button><Button asChild variant="outline" className="h-11 rounded-xl border-white/20 bg-transparent text-white hover:bg-white/10 hover:text-white"><Link href="/report">View sample evidence</Link></Button></div></div></section>
  <section className="border-b border-amber-200 bg-amber-50"><div className="mx-auto flex max-w-[1000px] items-start gap-3 px-5 py-5 text-sm leading-6 text-amber-950 sm:px-8"><CircleAlert className="mt-0.5 size-5 shrink-0 text-amber-700"/><p><strong>Private beta scope:</strong> methodology version <code>readiness-v0.1</code> currently scores only live website crawlability, content structure, and entity signals. Actual AI mentions, recommendations, citations, and positions remain unscored until named answer surfaces are connected.</p></div></section>
  <section className="mx-auto max-w-[1240px] px-5 py-20 sm:px-8"><div className="grid gap-8 lg:grid-cols-2"><Card className="rounded-[26px] border-blue-200 bg-blue-50/40 py-0 shadow-none"><CardContent className="p-7 sm:p-9"><span className="grid size-11 place-items-center rounded-2xl bg-blue-600 text-white"><Bot className="size-5"/></span><p className="mt-7 text-xs font-bold uppercase tracking-[.14em] text-blue-600">What happened</p><h2 className="mt-2 text-3xl font-extrabold">Actual AI visibility</h2><p className="mt-4 leading-7 text-slate-600">Did defined AI surfaces mention, cite, or recommend the brand for relevant questions in a specific market and language?</p><div className="mt-6 rounded-2xl bg-white p-4 text-sm font-bold text-blue-800">Brand × Topic × Prompt × Language × Country × Engine × Run</div></CardContent></Card><Card className="rounded-[26px] border-violet-200 bg-violet-50/40 py-0 shadow-none"><CardContent className="p-7 sm:p-9"><span className="grid size-11 place-items-center rounded-2xl bg-violet-600 text-white"><FileSearch className="size-5"/></span><p className="mt-7 text-xs font-bold uppercase tracking-[.14em] text-violet-600">Why it may happen</p><h2 className="mt-2 text-3xl font-extrabold">AEO/GEO readiness</h2><p className="mt-4 leading-7 text-slate-600">Can systems crawl, interpret, extract, trust, and connect the website’s content and entity signals?</p><div className="mt-6 rounded-2xl bg-white p-4 text-sm font-bold text-violet-800">A technically strong site can still have weak actual visibility — and vice versa.</div></CardContent></Card></div></section>
  <section className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-[1240px] px-5 py-20 sm:px-8"><div className="mb-10 max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.14em] text-blue-600">Score dimensions</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">Five views, never one unexplained number.</h2></div><div className="grid gap-4 md:grid-cols-2">{dimensions.map(([title,desc],i)=><Card key={title} className={`rounded-[20px] border-slate-200 py-0 shadow-none ${i===0?"md:col-span-2":""}`}><CardContent className="flex gap-5 p-6"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-sm font-extrabold text-blue-600">0{i+1}</span><div><h3 className="font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{desc}</p></div></CardContent></Card>)}</div></div></section>
  <section className="mx-auto max-w-[1240px] px-5 py-20 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.68fr_1.32fr]"><div><p className="text-sm font-bold uppercase tracking-[.14em] text-blue-600">Measurement flow</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight">From context to defensible evidence.</h2><p className="mt-4 leading-7 text-slate-600">The same framework applies across languages, while prompt generation and market interpretation stay local.</p></div><div className="space-y-3">{stages.map(([n,title,desc])=><div key={n} className="flex gap-4 rounded-2xl border border-slate-200 bg-white p-5"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#07111f] text-sm font-bold text-white">{n}</span><div><h3 className="font-extrabold">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{desc}</p></div></div>)}</div></div></section>
  <section className="bg-slate-100"><div className="mx-auto max-w-[1240px] px-5 py-20 sm:px-8"><div className="mb-10"><p className="text-sm font-bold uppercase tracking-[.14em] text-blue-600">Non-negotiable safeguards</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight">What Recomvia will not claim.</h2></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[
    [Scale,"No guaranteed ranking","Third-party systems remain outside our control."],[Repeat2,"No single-run certainty","Repeated runs and confidence labels expose volatility."],[Globe2,"No language shortcuts","Arabic and English are separate market measurements."],[ShieldCheck,"No hidden methodology","Metrics must be measurable, explainable, repeatable, and actionable."]
  ].map(([Icon,title,desc])=><Card key={title as string} className="rounded-[22px] border-slate-200 py-0 shadow-none"><CardContent className="p-6"><Icon className="size-5 text-blue-600"/><h3 className="mt-6 font-extrabold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{desc as string}</p></CardContent></Card>)}</div><div className="mt-8 grid gap-4 sm:grid-cols-3">{[[Clock3,"Timestamp every run"],[BarChart3,"Show confidence"],[CircleAlert,"State limitations"]].map(([Icon,label])=><div key={label as string} className="flex items-center gap-3 rounded-2xl bg-white p-4 text-sm font-bold"><Icon className="size-4 text-cyan-600"/>{label as string}<Check className="ml-auto size-4 text-emerald-600"/></div>)}</div></div></section>
 </main></PublicShell>}
